spring:
  datasource:
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:application;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    show-sql: true
    database: H2

server:
  servlet:
    context-path: /
